fail if dependencies are missing
libbitcoin/libbitcoin-build pull request #224
Opened 2020-10-23 06:17 UTC by xloem

moved from https://github.com/libbitcoin/libbitcoin-system/pull/1171

I have no experience with GSL, but this appears to work.

2020-11-07 22:59 UTC, evoskuil requested changes
Thanks, sorry for the review delay.

2020-11-07 22:59 UTC, evoskuil commented on templates/gsl.configure.ac
> +.       define my.option = my.configure->option(option.name =  my.dependency.option)
Style: double space after `=`

2020-11-07 22:59 UTC, evoskuil commented on templates/gsl.configure.ac
> +.       define my.opttype = get_option_type(my.option)
`my.opttype`

Style: avoid abbreviations and don't combine distinct words. For example, use `my.option.type`.

2020-11-08 11:32 UTC, xloem commented
Thanks for the review.  I'm afraid I don't have this set up right now to test changes; it could possibly be quite some time.  Feel free to close if it's in the way; otherwise I'll get back to it eventually.

2020-11-08 18:36 UTC, evoskuil commented
No worries, I’ll make the edits.

2020-11-29 03:54 UTC, evoskuil commented
Added with suggested style changes in new PR. Thanks!

2020-11-29 03:54 UTC, closed without merging

2020-12-03 14:59 UTC, xloem commented
Thanks for sorting this out.